config/routes.rb
DbcOverflow::Application.routes.draw do
  root to: 'questions#index'

  resources :questions do
    resources :answers, only: :create
  end
  resources :answers, except: :create
  resources :votes, only: :create
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :votes, as: :voteable
  attr_accessible :title, :content, :question_id
end

app/models/imgur.rb
class Imgur
  include HTTParty
  headers 'Content-Type' => 'application/json', "Authorization" => "Client-ID 691c16a3ed9cf63"
  base_uri 'https://api.imgur.com'

  def initialize(image)
    @options = { body: {image: image}.to_json }
  end

  def upload
    self.class.post("/3/image", @options)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_many :votes, as: :voteable
  attr_accessible :title, :content

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :direction
  belongs_to :voteable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find params[:question_id]
    @question.answers.create(params[:answer])
    redirect_to question_path(@question)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.new
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @question = Question.find params[:id]
  end

  def create
    @question = Question.create(title: params[:question][:title], content: params[:question][:content])
    # @image = params[:question][:picture].tempfile
    @question.img_url = HTTParty.post("https://api.imgur.com/3/image", :body => { :image => Base64.encode64(params[:question][:picture].tempfile.read) }.to_json, :headers => { 'Content-Type' => 'application/json', "Authorization" => "Client-ID 691c16a3ed9cf63" } )["data"]["link"]
    @question.save
    HardWorker.perform_async
    redirect_to questions_path
  end

  def destroy
    @question = Question.find params[:id]
    @question.destroy
    redirect_to questions_path
  end

  def edit
    @question = Question.find params[:id]
  end

  def update
    @question = Question.find params[:id]
    @question.update_attributes params[:question]
    redirect_to question_path @question
  end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @voteable = if params[:type] == "answer"
      Answer.find(params[:answer])
    elsif params[:type] == "question"
      Question.find(params[:question])
    end
    @voteable.votes.create(direction: params[:direction])
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "skin", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :picture %>
  <%= f.file_field :picture %>
  <%= f.submit "Submit", :class => 'submit'%>
<% end %>

app/views/questions/confirmation_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>A Question Has Posted!</h1>
    <p>A question has just posted.  Here it is: </p>
    <ul>
      <li><%= @question.title %>  </li>
      <li><%= @question.content %></li>
    </ul>

    </body>
</html>

app/views/questions/confirmation_email.text.erb
Welcome to FunkyTown.com
===============================================

A Question Has Posted!
Thanks for posting and have a great day!

A question has just posted.  Here it is:
<%= @question.title %>
<%= @question.content %>

app/views/questions/edit.html.erb
<%= render "form" %>

app/views/questions/index.html.erb
<header>
  <h1>Funky Town Questions</h1>
</header>

<div class="create_question_form">
  <%= render "form" %>
</div>

<% @questions.each do |question| %>
  <div class="show_questions">
    <h2><%= link_to question.title, question_path(question) %></h2>
    <p><%= question.content %></p>
    <%= div_for(question) do %>

      <%= link_to votes_path(direction: "up", question: question.id, type: "question"), method: "POST", remote: true, class: "vote-up", id: "upvote" do %>
        <i class="fa fa-caret-square-o-up"></i>
      <% end %>

      <p>Rating:</p>
      <p><%= (question.votes.where(direction: "up").count - question.votes.where(direction: "down").count) %></p>

      <%= link_to votes_path(direction: "down", question: question.id, type: "question"), method: "POST", remote: true, class: "vote-down", id: "downvote" do %>
        <i class="fa fa-caret-square-o-down"></i>
      <% end %>

    <% end %>
  </div>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.content %></p>
<%= image_tag(@question.img_url) %>
<%= div_for(@question) do %>
  <%= link_to "upvote", votes_path(direction: "up", question: @question.id, type: "question"), method: "POST" %>
  <%= link_to "downvote", votes_path(direction: "down", question: @question.id, type: "question"), method: "POST" %>
  <p>Votes: <%= (@question.votes.where(direction: "up").count - @question.votes.where(direction: "down").count) %></p>
<% end %>

<%= button_to "Delete", { action: "destroy", id: @question.id }, method: :delete %>

<%= form_for [@question, @answer] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit "Answer" %>
<% end %>

<% @question.answers.each do |answer| %>
  <h2><%= answer.title %></h2>
  <p><%= answer.content %></p>
  <%= div_for(answer) do %>
    <%= link_to "upvote", votes_path(direction: "up", answer: answer.id, type: "answer"), method: "POST" %>
    <%= link_to "downvote", votes_path(direction: "down", answer: answer.id, type: "answer"), method: "POST" %>
    <p>Votes: <%= (answer.votes.where(direction: "up").count - answer.votes.where(direction: "down").count) %></p>
  <% end %>
<% end %>